/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author lalit
 */
public class altaArticulo extends javax.swing.JFrame {

    /**
     * Creates new form altaArticulo
     */
    public altaArticulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alimentoBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        insumoBtn = new javax.swing.JButton();
        merchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alimentoBtn.setBackground(new java.awt.Color(255, 51, 51));
        alimentoBtn.setFont(new java.awt.Font("Circus", 0, 36)); // NOI18N
        alimentoBtn.setForeground(new java.awt.Color(255, 255, 255));
        alimentoBtn.setText("Alimento");
        alimentoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alimentoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(alimentoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 270, 80));

        volverBtn.setBackground(new java.awt.Color(255, 51, 51));
        volverBtn.setFont(new java.awt.Font("Circus", 0, 36)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        getContentPane().add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 220, 80));

        insumoBtn.setBackground(new java.awt.Color(255, 51, 51));
        insumoBtn.setFont(new java.awt.Font("Circus", 0, 36)); // NOI18N
        insumoBtn.setForeground(new java.awt.Color(255, 255, 255));
        insumoBtn.setText("Insumo");
        insumoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insumoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(insumoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 270, 80));

        merchBtn.setBackground(new java.awt.Color(255, 51, 51));
        merchBtn.setFont(new java.awt.Font("Circus", 0, 36)); // NOI18N
        merchBtn.setForeground(new java.awt.Color(255, 255, 255));
        merchBtn.setText("Merch");
        merchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(merchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 270, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/altaArticulo.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1233, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void insumoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insumoBtnActionPerformed
        altaInsumo ventana = new altaInsumo();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_insumoBtnActionPerformed

    private void merchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merchBtnActionPerformed
        altaMerch ventana = new altaMerch();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_merchBtnActionPerformed

    private void alimentoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alimentoBtnActionPerformed
        altaAlimento ventana = new altaAlimento();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_alimentoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altaArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altaArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altaArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altaArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altaArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alimentoBtn;
    private javax.swing.JButton insumoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton merchBtn;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
