/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Erick
 */
public class altaEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form altaEmpleados
     */
    public altaEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverBtn = new javax.swing.JButton();
        artistaBtn = new javax.swing.JButton();
        trabajadorBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverBtn.setBackground(new java.awt.Color(255, 51, 51));
        volverBtn.setFont(new java.awt.Font("Circus", 0, 36)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        getContentPane().add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, 270, 100));

        artistaBtn.setBackground(new java.awt.Color(255, 51, 51));
        artistaBtn.setFont(new java.awt.Font("Circus", 0, 36)); // NOI18N
        artistaBtn.setForeground(new java.awt.Color(255, 255, 255));
        artistaBtn.setText("Artista");
        artistaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(artistaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 310, 100));

        trabajadorBtn.setBackground(new java.awt.Color(255, 51, 51));
        trabajadorBtn.setFont(new java.awt.Font("Circus", 0, 36)); // NOI18N
        trabajadorBtn.setForeground(new java.awt.Color(255, 255, 255));
        trabajadorBtn.setText("Trabajador");
        trabajadorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabajadorBtnActionPerformed(evt);
            }
        });
        getContentPane().add(trabajadorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 310, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RegEmpl.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1080, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void artistaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistaBtnActionPerformed
        altaArtista ventana = new altaArtista();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_artistaBtnActionPerformed

    private void trabajadorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabajadorBtnActionPerformed
        altaTrabajador ventana = new altaTrabajador();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_trabajadorBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton artistaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton trabajadorBtn;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
