/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Font;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/**
 *
 * @author lalit
 */
public class listaArticulos extends javax.swing.JFrame {
    
    String texto = "";
    
    /**
     * Creates new form listaProductos
     */
    public listaArticulos() {
        initComponents();
        setTexto();
        lista.setText(texto);
        Font font = lista.getFont();
        float size = font.getSize() + 15.0f;
        lista.setFont( font.deriveFont(size) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eliminarTXT = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lista.setColumns(20);
        lista.setRows(5);
        jScrollPane1.setViewportView(lista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 540, 260));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Circus", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 270, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Escriba el id del producto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("que desea eliminar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, -1, -1));

        eliminarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTXTActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 150, 30));

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Circus", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ListadoProd.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void eliminarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarTXTActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            String eliminarText = eliminarTXT.getText();
            int idEliminar = Integer.parseInt(eliminarText);
            boolean seEncontro = false;
            
            for (int i = 0; i < main.alimentos.size(); i++) {
                if(main.alimentos.get(i).id == idEliminar){
                    main.alimentos.remove(i);
                    seEncontro = true;
                    break;
                }
            }
            
            for (int i = 0; i < main.merch.size(); i++) {
                if(main.merch.get(i).id == idEliminar){
                    main.merch.remove(i);
                    seEncontro = true;
                    break;
                }
            }
            
            for (int i = 0; i < main.insumos.size(); i++) {
                if(main.insumos.get(i).id == idEliminar){
                    main.insumos.remove(i);
                    seEncontro = true;
                    break;
                }
            }
            
            if(seEncontro == false){
                JOptionPane.showMessageDialog(rootPane, "No se encontro el id del producto");
            }
            texto = "";
            setTexto();
            lista.setText(texto);
        }catch(InputMismatchException | NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Se introdujeron datos invalidos, intentelo de nuevo");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaArticulos().setVisible(true);
            }
        });
    }
    
    public void setTexto(){
        if(main.alimentos.size() != 0){
            texto+="Alimentos:\n";
            for (int i = 0; i < main.alimentos.size(); i++) {
                texto += main.alimentos.get(i).Datos();
            }
        }
        
        if (main.merch.size() != 0) {
            texto+="\nMerch:\n";
            for (int i = 0; i < main.merch.size(); i++) {
                texto += main.merch.get(i).Datos();
            }
        }
        
        if (main.insumos.size() != 0) {
            texto+="\nInsumos:\n";
            for (int i = 0; i < main.insumos.size(); i++) {
                texto += main.insumos.get(i).Datos();
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eliminarTXT;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lista;
    // End of variables declaration//GEN-END:variables
}
